from typing import NoReturn

from fastapi import HTTPException, status

from app.schemas.player import ErrorDetail, ErrorResponse


class PlayerErrorCodes:
    PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND"
    INVALID_PLAYER_ID = "INVALID_PLAYER_ID"
    INVALID_QUEST_STATUS = "INVALID_QUEST_STATUS"
    REGION_NOT_FOUND = "REGION_NOT_FOUND"
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    AUDIT_WRITE_FAILED = "AUDIT_WRITE_FAILED"
    TRACE_ID_MISSING = "TRACE_ID_MISSING"
    TASK_DISPATCH_FAILED = "TASK_DISPATCH_FAILED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    QUEST_NOT_FOUND = "QUEST_NOT_FOUND"
    QUEST_ALREADY_ACCEPTED = "QUEST_ALREADY_ACCEPTED"
    QUEST_NOT_ACTIVE = "QUEST_NOT_ACTIVE"
    QUEST_INVALID_STATE_TRANSITION = "QUEST_INVALID_STATE_TRANSITION"
    QUEST_ALREADY_COMPLETED = "QUEST_ALREADY_COMPLETED"
    QUEST_OBJECTIVES_INCOMPLETE = "QUEST_OBJECTIVES_INCOMPLETE"
    QUEST_REWARD_GRANT_FAILED = "QUEST_REWARD_GRANT_FAILED"
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    INSUFFICIENT_QUANTITY = "INSUFFICIENT_QUANTITY"
    INVALID_ITEM_TYPE = "INVALID_ITEM_TYPE"
    REPUTATION_REGION_NOT_FOUND = "REPUTATION_REGION_NOT_FOUND"
    INVALID_REPUTATION_AMOUNT = "INVALID_REPUTATION_AMOUNT"
    REPUTATION_LOCKED = "REPUTATION_LOCKED"
    CONTRIBUTION_PLAYER_NOT_FOUND = "CONTRIBUTION_PLAYER_NOT_FOUND"
    INVALID_CONTRIBUTION_AMOUNT = "INVALID_CONTRIBUTION_AMOUNT"
    ACHIEVEMENT_NOT_FOUND = "ACHIEVEMENT_NOT_FOUND"
    ACHIEVEMENT_ALREADY_UNLOCKED = "ACHIEVEMENT_ALREADY_UNLOCKED"
    ACHIEVEMENT_KEY_EXISTS = "ACHIEVEMENT_KEY_EXISTS"
    ACHIEVEMENT_REWARD_ALREADY_CLAIMED = "ACHIEVEMENT_REWARD_ALREADY_CLAIMED"
    ACHIEVEMENT_NOT_ACTIVE = "ACHIEVEMENT_NOT_ACTIVE"
    INVALID_ACHIEVEMENT_RARITY = "INVALID_ACHIEVEMENT_RARITY"
    INVALID_ACHIEVEMENT_CATEGORY = "INVALID_ACHIEVEMENT_CATEGORY"
    INVALID_EXPERIENCE_AMOUNT = "INVALID_EXPERIENCE_AMOUNT"
    MAX_LEVEL_REACHED = "MAX_LEVEL_REACHED"
    FRIEND_REQUEST_ALREADY_SENT = "FRIEND_REQUEST_ALREADY_SENT"
    FRIEND_REQUEST_NOT_FOUND = "FRIEND_REQUEST_NOT_FOUND"
    FRIEND_REQUEST_NOT_PENDING = "FRIEND_REQUEST_NOT_PENDING"
    ALREADY_FRIENDS = "ALREADY_FRIENDS"
    CANNOT_FRIEND_SELF = "CANNOT_FRIEND_SELF"
    FRIEND_NOT_FOUND = "FRIEND_NOT_FOUND"
    FRIEND_BLOCKED = "FRIEND_BLOCKED"
    NOT_FRIENDS = "NOT_FRIENDS"
    MESSAGE_TOO_LONG = "MESSAGE_TOO_LONG"
    MESSAGE_EMPTY = "MESSAGE_EMPTY"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    CANNOT_DELETE_OTHER_MESSAGE = "CANNOT_DELETE_OTHER_MESSAGE"

    # 公会相关错误码
    GUILD_NAME_EXISTS = "GUILD_NAME_EXISTS"
    GUILD_NOT_FOUND = "GUILD_NOT_FOUND"
    ALREADY_IN_GUILD = "ALREADY_IN_GUILD"
    NOT_IN_GUILD = "NOT_IN_GUILD"
    NOT_GUILD_LEADER = "NOT_GUILD_LEADER"
    NOT_GUILD_OFFICER = "NOT_GUILD_OFFICER"
    CANNOT_REMOVE_LEADER = "CANNOT_REMOVE_LEADER"
    GUILD_FULL = "GUILD_FULL"
    CANNOT_LEAVE_AS_LEADER = "CANNOT_LEAVE_AS_LEADER"

    # 装备相关错误码
    INVALID_EQUIPMENT_SLOT = "INVALID_EQUIPMENT_SLOT"
    EQUIPMENT_SLOT_OCCUPIED = "EQUIPMENT_SLOT_OCCUPIED"
    ITEM_NOT_EQUIPPABLE = "ITEM_NOT_EQUIPPABLE"
    CANNOT_UNEQUIP_EMPTY_SLOT = "CANNOT_UNEQUIP_EMPTY_SLOT"
    LEVEL_REQUIREMENT_NOT_MET = "LEVEL_REQUIREMENT_NOT_MET"
    EQUIPMENT_NOT_FOUND = "EQUIPMENT_NOT_FOUND"


def raise_player_error(
    code: str,
    message: str,
    request_id: str,
    status_code: int = status.HTTP_400_BAD_REQUEST,
    details: list[ErrorDetail] | None = None,
) -> NoReturn:
    raise HTTPException(
        status_code=status_code,
        detail=ErrorResponse(
            code=code,
            message=message,
            request_id=request_id,
            details=details or [],
        ).model_dump(),
    )
