from typing import NoReturn

from fastapi import HTTPException, status

from app.schemas.player import ErrorDetail, ErrorResponse


class PlayerErrorCodes:
    PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND"
    INVALID_PLAYER_ID = "INVALID_PLAYER_ID"
    INVALID_QUEST_STATUS = "INVALID_QUEST_STATUS"
    REGION_NOT_FOUND = "REGION_NOT_FOUND"
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    AUDIT_WRITE_FAILED = "AUDIT_WRITE_FAILED"
    TRACE_ID_MISSING = "TRACE_ID_MISSING"
    TASK_DISPATCH_FAILED = "TASK_DISPATCH_FAILED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    QUEST_NOT_FOUND = "QUEST_NOT_FOUND"
    QUEST_ALREADY_ACCEPTED = "QUEST_ALREADY_ACCEPTED"
    QUEST_NOT_ACTIVE = "QUEST_NOT_ACTIVE"
    QUEST_INVALID_STATE_TRANSITION = "QUEST_INVALID_STATE_TRANSITION"
    QUEST_ALREADY_COMPLETED = "QUEST_ALREADY_COMPLETED"
    QUEST_OBJECTIVES_INCOMPLETE = "QUEST_OBJECTIVES_INCOMPLETE"
    QUEST_REWARD_GRANT_FAILED = "QUEST_REWARD_GRANT_FAILED"
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    INSUFFICIENT_QUANTITY = "INSUFFICIENT_QUANTITY"
    INVALID_ITEM_TYPE = "INVALID_ITEM_TYPE"
    REPUTATION_REGION_NOT_FOUND = "REPUTATION_REGION_NOT_FOUND"
    INVALID_REPUTATION_AMOUNT = "INVALID_REPUTATION_AMOUNT"
    REPUTATION_LOCKED = "REPUTATION_LOCKED"


def raise_player_error(
    code: str,
    message: str,
    request_id: str,
    status_code: int = status.HTTP_400_BAD_REQUEST,
    details: list[ErrorDetail] | None = None,
) -> NoReturn:
    raise HTTPException(
        status_code=status_code,
        detail=ErrorResponse(
            code=code,
            message=message,
            request_id=request_id,
            details=details or [],
        ).model_dump(),
    )
